import pandas as pd

def flatten_multiindex(df: pd.DataFrame) -> pd.DataFrame:
    """Flattens multi-index columns if generated by yf.download."""
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df